### PR TITLE
Added class for shopping cart

### PR DESCRIPTION
**Pull request by Chinoms**
Some functionality is not available yet, including online payment option and adding of products by users.
@prezine Kindly design the database and commit it so we can work with it.

### CODE REVIEW

**Comment by prezine** [comment]
Awesome Cart class, your use of `$attributes` I'd love to understand, what your definition of attr is.

**Comment by Chinoms** [comment]
Thanks.
`$attributes` is an array that contains attributes of an item like the size, price, colour and other descriptive stuff.

**Comment by prezine** [comment]
Aii, I'd review and make merge.
I'll also send the database through.
Expect database modification since I'll be adding db for each features on the go. Thanks

**Comment by Chinoms** [comment]
And it'll be kind on your part if you could make a UI for the dashboard which would include adding products to the database.  That way, it would be easier for me to round up.

**Comment by prezine** [comment]
Okay I would do just that

**Pull request merged**
